--liquibase formatted sql

--changeset jhr:2
CREATE TABLE SITD.TARGET
(
  BOARD   CHAR(36) NOT NULL,
  START_X INT      NOT NULL,
  START_Y INT      NOT NULL,
  END_X   INT      NOT NULL,
  END_Y   INT      NOT NULL,
  CONSTRAINT TARGET_PK PRIMARY KEY (BOARD, START_X, START_Y, END_X, END_Y)
);
CREATE INDEX TARGET_BOARD_IDX ON SITD.TARGET (BOARD);