--liquibase formatted sql

--changeset jhr:4
CREATE TABLE SITD.PLAYER_FEATURE
(
  PLAYER  CHAR(36)    NOT NULL,
  FEATURE VARCHAR(32) NOT NULL,
  CONSTRAINT PLAYER_FEATURE_PK PRIMARY KEY (PLAYER, FEATURE)
);