--liquibase formatted sql

--changeset jhr:6
CREATE TABLE SITD.PRINCIPAL_ROLE
(
  PRINCIPAL CHAR(36)    NOT NULL,
  ROLE      VARCHAR(32) NOT NULL,
  CONSTRAINT PRINCIPAL_ROLE_PK PRIMARY KEY (PRINCIPAL, ROLE)
);
CREATE INDEX SITD.PRINCIPAL_IDX ON SITD.PRINCIPAL_ROLE (PRINCIPAL);
CREATE INDEX SITD.PR_ROLE_IDX ON SITD.PRINCIPAL_ROLE (ROLE);