--liquibase formatted sql

--changeset jhr:8
CREATE TABLE SITD.SHOT
(
  GAME    CHAR(36)  NOT NULL,
  X       INT       NOT NULL,
  Y       INT       NOT NULL,
  ORDINAL TIMESTAMP NOT NULL,
  CONSTRAINT SHOT_GAME_FK FOREIGN KEY (GAME) REFERENCES SITD.GAME (ID)
);
CREATE INDEX SITD.SHOT_GAME_IDX ON SITD.SHOT (GAME, ORDINAL);
CREATE INDEX SITD.ROLE_IDX ON SITD.PRINCIPAL_ROLE (ROLE);