CREATE SCHEMA SITD AUTHORIZATION admin;

CREATE TABLE SITD.BOARD
(
    ID CHAR(36)                    PRIMARY KEY NOT NULL,
    WIDTH INT NOT NULL,
    HEIGHT INT NOT NULL,
    CREATED TIMESTAMP DEFAULT current_timestamp NOT NULL
);

CREATE TABLE SITD.TARGET
(
  BOARD   CHAR(36)              NOT NULL,
  START_X INT                   NOT NULL,
  START_Y INT                   NOT NULL,
  END_X   INT                   NOT NULL,
  END_Y   INT                   NOT NULL,
  CONSTRAINT TARGET_PK PRIMARY KEY (BOARD, START_X, START_Y, END_X, END_Y)
);
CREATE INDEX TARGET_BOARD_IDX ON SITD.TARGET (BOARD);

CREATE TABLE SITD.PLAYER
(
  ID      CHAR(36)              PRIMARY KEY   NOT NULL,
  NAME    VARCHAR(256)                        NOT NULL,
  CREATED TIMESTAMP DEFAULT current_timestamp NOT NULL
);

CREATE TABLE SITD.GAME
(
  ID      CHAR(36)                            PRIMARY KEY   NOT NULL,
  PLAYER  CHAR(36)                            NOT NULL,
  BOARD   CHAR(36)                            NOT NULL,
  CREATED TIMESTAMP DEFAULT current_timestamp NOT NULL,
  CONSTRAINT GAME_BOARD_FK FOREIGN KEY (BOARD) REFERENCES SITD.BOARD (ID),
  CONSTRAINT GAME_PLAYER_FK FOREIGN KEY (PLAYER) REFERENCES SITD.PLAYER (ID)
);

CREATE TABLE SITD.SHOT
(
  GAME CHAR(36)     NOT NULL,
  X    INT          NOT NULL,
  Y    INT          NOT NULL,
  ORDINAL TIMESTAMP NOT NULL,
  CONSTRAINT SHOT_GAME_FK FOREIGN KEY (GAME) REFERENCES SITD.GAME (ID)
);
CREATE INDEX SHOT_GAME_IDX ON SITD.SHOT (GAME, ORDINAL);