CREATE TABLE SITD.BOARD
(
  ID      CHAR(36) PRIMARY KEY                NOT NULL,
  WIDTH   INT                                 NOT NULL,
  HEIGHT  INT                                 NOT NULL,
  CREATED TIMESTAMP DEFAULT current_timestamp NOT NULL
);

CREATE TABLE SITD.TARGET
(
  BOARD   CHAR(36) NOT NULL,
  START_X INT      NOT NULL,
  START_Y INT      NOT NULL,
  END_X   INT      NOT NULL,
  END_Y   INT      NOT NULL,
  CONSTRAINT TARGET_PK PRIMARY KEY (BOARD, START_X, START_Y, END_X, END_Y)
);
CREATE INDEX TARGET_BOARD_IDX ON SITD.TARGET (BOARD);

CREATE TABLE SITD.PLAYER
(
  ID      CHAR(36) PRIMARY KEY                NOT NULL,
  NAME    VARCHAR(256)                        NOT NULL,
  CREATED TIMESTAMP DEFAULT current_timestamp NOT NULL
);

CREATE TABLE SITD.PLAYER_FEATURE
(
  PLAYER  CHAR(36)    NOT NULL,
  FEATURE VARCHAR(32) NOT NULL,
  CONSTRAINT PLAYER_FEATURE_PK PRIMARY KEY (PLAYER, FEATURE)
);

CREATE TABLE SITD.PRINCIPAL
(
  ID       CHAR(36) PRIMARY KEY                NOT NULL,
  PASSWORD CHAR(40)                            NOT NULL,
  CREATED  TIMESTAMP DEFAULT current_timestamp NOT NULL
);

CREATE TABLE SITD.PRINCIPAL_ROLE
(
  PRINCIPAL CHAR(36)    NOT NULL,
  ROLE      VARCHAR(32) NOT NULL,
  CONSTRAINT PRINCIPAL_ROLE_PK PRIMARY KEY (PRINCIPAL, ROLE)
);
CREATE INDEX SITD.PRINCIPAL_IDX ON SITD.PRINCIPAL_ROLE (PRINCIPAL);
CREATE INDEX SITD.PR_ROLE_IDX ON SITD.PRINCIPAL_ROLE (ROLE);

CREATE TABLE SITD.GAME
(
  ID      CHAR(36) PRIMARY KEY                NOT NULL,
  PLAYER  CHAR(36)                            NOT NULL,
  BOARD   CHAR(36)                            NOT NULL,
  CREATED TIMESTAMP DEFAULT current_timestamp NOT NULL,
  CONSTRAINT GAME_BOARD_FK FOREIGN KEY (BOARD) REFERENCES SITD.BOARD (ID),
  CONSTRAINT GAME_PLAYER_FK FOREIGN KEY (PLAYER) REFERENCES SITD.PLAYER (ID)
);

CREATE TABLE SITD.SHOT
(
  GAME    CHAR(36)  NOT NULL,
  X       INT       NOT NULL,
  Y       INT       NOT NULL,
  ORDINAL TIMESTAMP NOT NULL,
  CONSTRAINT SHOT_GAME_FK FOREIGN KEY (GAME) REFERENCES SITD.GAME (ID)
);
CREATE INDEX SITD.SHOT_GAME_IDX ON SITD.SHOT (GAME, ORDINAL);
CREATE INDEX SITD.ROLE_IDX ON SITD.PRINCIPAL_ROLE (ROLE);