DROP TABLE SITD.SHOT;
DROP TABLE SITD.GAME;
DROP TABLE SITD.PLAYER_FEATURE;
DROP TABLE SITD.PLAYER;
DROP TABLE SITD.PRINCIPAL_ROLE;
DROP TABLE SITD.PRINCIPAL;
DROP TABLE SITD.TARGET;
DROP TABLE SITD.BOARD;
DROP SCHEMA SITD RESTRICT;